theme: jekyll-theme-slate
show_downloads: true
title: antibrand system
tagline: A generic website management system forked from WordPress 4.9.8.
image: https://repository-images.githubusercontent.com/219322128/443b3d80-0225-11ea-8c55-56cd08b60579